### ISSUE TITLE
Configure texstudio -> General --> "Check Now" is not working

### ISSUE THREAD

**Issue by pagenum** [texstudio-org/texstudio#1969]
### Environment
- TeXstudio: 4.1.1
- Qt: 6.2.1
- OS: Windows 10
- TeX distribution: texlive

### Expected behavior
A message box with text 'texstudio is up-to-date' appears
Time of 'Last Checked' changes

### Actual behavior
Nothing happened

### How to reproduce
Press "Check Now" button

**Comment by sunderme** [comment]
I have noticed and I have no idea why.
It is not the code, but the distributed dlls. Probably one is missing, but no idea which.

**Comment by Lleafll** [comment]
windeployqt deploys a tls folder with these dlls:
````
qcertonlybackend.dll
qopensslbackend.dll
qschannelbackend.dll
````
Adding these to the packaged TeXstudio binaries for Windows fixes the tls initialization issues and thus the update check.

**Comment by benibela** [comment]
It probably does not need all of these dlls (schannel is the Microsoft TLS implementation)

**Comment by Lleafll** [comment]
You are right, qopensslbackend.dll is sufficient (at least in this context).

**Comment by sunderme** [comment]
fixed as suggested

**Comment by amelchiori5** [comment]
Hi everybody, I got what the error is on this topic. The only thing is that I'm not able to understand how to fix it on my own!

I donwnloaded the missing _qopensslbackend.dll_, but I do not understand what to do with it.

Help will be much appreciated!

**Comment by sunderme** [comment]
4.1.2 should work.

**Comment by amelchiori5** [comment]
@sunderme I have 4.1.2 installed on my PC and it is still not working atm

**Comment by sunderme** [comment]
apparently it works starting with the dev. build after the 4.1.2 release.
So, you can use one of those (https://github.com/texstudio-org/texstudio/actions/workflows/cd.yml)

**Comment by pagenum** [comment]
> 



> 4.1.2 should work.

I also installed 4.1.2
Still no update check
