### ISSUE TITLE
Hyperlinks do not work in internal viewer

### ISSUE THREAD

**Issue by matthiasfabry** [texstudio-org/texstudio#4204]
When navigating in the internal pdf viewer, clicking on hyperlinks to sections, figures, etc... has no effect. Acrobat has no problem using the hyperlinks.

### Environment
- TeXstudio 4.8.9 (git 4.8.9)
- Using Qt Version 6.9.2, compiled with Qt 6.9.2 R
- MacOS 15.6.1
- TeX distribution: texlive

### Expected behavior

the viewer jumps to the page where the link points

### Actual behavior

no effect

### How to reproduce

```latex
\documentclass{article}
\usepackage{hyperref, lipsum}

\begin{document}
    \section{hello}\label{hello}
    \lipsum
    
    link to \ref{hello}.
\end{document}
```

**Comment by muzimuzhi** [comment]
> * TeXstudio 4.8.9 (git 4.8.9)
> * [...]
> * MacOS 15.6.1

Works for me, in TeXstudio 4.9.0beta2 on macOS 14.8.1, Intel Chip.

Related issue: #4173. But the latter should have been fixed in 4.8.9.

**Comment by sunderme** [comment]
4.8.9, OSX m1 works as expected

**Comment by matthiasfabry** [comment]
#4173 definitely helped, switching modes in the taskbar somehow reenabled the links. I normally work in zoom (rectangle) mode, but switching to text selection and back fixed my issue. I'm closing because its likely gonna be hard to reproduce.

Thanks for pointing out #4173.

**Comment by clecap** [comment]
That is just to confirm that the problem still is there. I have it on

TeXstudio 4.9.5 (git 4.9.5)
Using Qt Version 6.11.1, compiled with Qt 6.11.1 R

with Tahoe 26.3.1 (a) (25D771280a)

The suggestion provided here helped me solve it, but the bug as such still is there in the code and does show up.

**Comment by sunderme** [comment]
still works: QT 6.11 , Tahoe 26.5

**Comment by clecap** [comment]
Well...I do not know how to (re)produce that problem. An optimistic "works for me" does not really help us here. It also "works for me". I can't produce the problem. But I pretty much *had* the problem for some 3 annoying weeks - until I found the hint here, which helped me solve it.

That said: I am pretty much sure the problem still is somewhere lingering in the source code and it will show up again when some poor soul manages to do the same I or @matthiasfabry did for getting us in trouble...

**Comment by octaeder** [comment]
The phrases “Works here” or “Can’t reproduce” do not suggest that the issue is being questioned. They indicate that a reproducible test case is needed to analyze the problem. Without one, diagnosing the cause is nearly impossible with reasonable effort. Remember that open‑source projects typically operate with limited resources.

**Comment by sunderme** [comment]
This issue has a clear test case and that works here.

**Comment by clecap** [comment]
> This issue has a clear test case and that works here.

Sounds great. Thanx. Important info which puts, for me, a fresh aspect into this. 👍🏻
