### ISSUE TITLE
Feature Request: add special treatment for commands like "\newcount"

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#689]
As far as I guess, since cwl file only supports options inside braces (`{}`, `[]`, etc), commands that normally used without braces around their arguments and defines (mostly one of) their arguments as new macros are specially treated in `latexdocument.cpp`. For example, 
```latex
\def\newcmd<parameter text>{<def>} % and \edef, \gdef, \xdef
\newcount\mycount
```

However, there are other command that share the same syntax with `\newcount` but have not been specially treated. This will cause wrong highlight effect in txs, see
![image](https://user-images.githubusercontent.com/6376638/62860224-0fa50c00-bd32-11e9-9d36-ad6636919c37.png)
The full list of these `\newcount`-like commands is
```latex
\newdimen
\newskip
\newmuskip
\newbox
\newtoks
\newread
\newwrite
\newlanguage
\newfam
\newinsert
```

PS: These macros, plus `\newcount`, were originally introduced in plain tex format, and were then adopted by latex2e format. Hence one can see the occurrences of them both in documents about tex with plain tex (like [`texdoc texbytopic`](http://mirrors.ctan.org/info/texbytopic/TeXbyTopic.pdf), Chap. 31) and in documents about latex2e (like [`texdoc source2e`](http://mirrors.ctan.org/macros/latex/base/source2e.pdf), Sec. b.9).

The related source lines could be
https://github.com/texstudio-org/texstudio/blob/a7fd0a3dc064f685d68b8a6792bb825f4669a085/src/latexdocument.cpp#L838-L852

**Comment by sunderme** [comment]
I have implemented it in the cwl, see commit 99cafd4f0df6c49319cdc13b9891fc7672b8cdff

**Comment by muzimuzhi** [comment]
The added lines to cwl file only recognize usages with braces like 
```latex
\newbox{\somebox} % here txs recognizes \somebox as a new cmd
...
\somebox % here txs highlights \somebox as normal cmd
```

But what I want, and what is usually used in latex package source files is the form without braces:
```latex
\newbox\someBox % here txs highlights both \someBox as "unrecognized command"
...
\someBox
```
That is to say, commit https://github.com/texstudio-org/texstudio/commit/99cafd4f0df6c49319cdc13b9891fc7672b8cdff does not solve the question shown in the screenshot I have posted:
![image](https://user-images.githubusercontent.com/6376638/62860224-0fa50c00-bd32-11e9-9d36-ad6636919c37.png)

PS: Yes, the with-brace form (`\newbox{\someBox}`) is a valid form, but the no-brace form is the form most latex package writers use. For example, the latex2e kernel consistently uses the no-brace form. This means, txs will provides wrong highlight when openning package source files.

------

This may provide a clear description about my original question (or request)
 - Currently, if one can denote a no-brace and new-cmd cwl line for `\newbox` to support usages like `\newbox\someBox` where `\someBox` will be recognized as new defined command.
 - If it supports, how can one write cwl lines.
 - If it doesn't support, does there exist an easy way to support/implement?

And following is my trial and guess when I opened this isse
 - After some test (for example, writing `\newbox%<cmd%>#d`), I guessed that it doesn't support. And I directly used my guess in the original post.
 - Meanwhile, when reading the source code, I found that txs supports `\newcount\someCount` by specially handle `\newcount` in source code. (See the referred code lines in original post.) Hence I guess if we can support more `\newXXX` by changing the bool expression to something like
```cpp
if (cmd == "\\newcount" || cmd == "\\newbox" || ...)
```

**Comment by sunderme** [comment]
here it works fine
![2019-08-18-193548_3840x2160_scrot](https://user-images.githubusercontent.com/14033169/63228222-5d1cef80-c1f0-11e9-90ac-3e6d1b2152b8.png)

**Comment by sunderme** [comment]
have you placed a tex.cwl in your .config/texstudio/completion/user  ?

**Comment by muzimuzhi** [comment]
Your commit does meet my original request. I am so sorry.

Before today, I used a `cwl-test.cwl` file containing a line `\newbox{cmd}#dS` and a test tex file
```latex
\documentclass{article}
\usepackage{cwl-test}
\newbox\xxx
\newcount\zzz
\begin{document}
\xxx
\zzz
\end{document}
```
Then the problem persists when I directly open txs with the tex file. But when I delete and then re-type in the line `\newbox\xxx` in tex file, it works.

**Comment by muzimuzhi** [comment]
I will provide the rest cwl lines.

**Comment by muzimuzhi** [comment]
Commit https://github.com/texstudio-org/texstudio/commit/d538bab7c91e9b845e0be698d1aac49b7e9b2d77 is also related to (or resulted from) this issue.
